# Where things are
source:       .
destination:  ./_site
plugins_dir:  _plugins
layouts_dir:  _layouts
data_dir:     _data
includes_dir: _includes

# Handling Reading
safe:                 false
exclude:              ["Gemfile", "Gemfile.lock", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/"]
encoding:             "utf-8"
strict_front_matter: false

# Serving
detach:  false
port:    4000
host:    127.0.0.1
baseurl: "" # does not include hostname
show_dir_listing: false

# Outputting
permalink: pretty

# Site Settings
url:          http://mikelikesbikes.com/

openid_cfg:
  openid:
    server: http://www.myopenid.com/server
    delegate: http://mikelikesbikes.myopenid.com/
  openid2:
    local_id: http://mikelikesbikes.myopenid.com
    provider: http://www.myopenid.com/server
  x_xrds_location: http://www.myopenid.com/xrds?username=mikelikesbikes.myopenid.com

navigation:
  contact: Contact
  resume: Resume

