safe:         false
baseurl:      /
url:          http://mikelikesbikes.com/

source:       .
destination:  ./_site
exclude:      [Gemfile, Gemfile.lock, .ruby-version, bin, Procfile, config.ru]

openid_cfg:
  openid:
    server: http://www.myopenid.com/server
    delegate: http://mikelikesbikes.myopenid.com/
  openid2:
    local_id: http://mikelikesbikes.myopenid.com
    provider: http://www.myopenid.com/server
  x_xrds_location: http://www.myopenid.com/xrds?username=mikelikesbikes.myopenid.com

navigation:
  contact: Contact
  resume: Resume

